spring.application.name=SGC

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sgc}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:110105}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:certs/sgc-dev.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=changeit
server.ssl.key-alias=te-c28233cb-f790-4a6e-8348-a601d200b45e
