CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    login VARCHAR(60) NOT NULL UNIQUE,
    senha VARCHAR(120) NOT NULL,
    perfil VARCHAR(20) NOT NULL
);

CREATE TABLE equipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    local VARCHAR(100) NOT NULL
);

CREATE TABLE campeonatos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_campeonato_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE partidas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora TIMESTAMP NOT NULL,
    placar_mandante INTEGER,
    placar_visitante INTEGER,
    numero_rodada INTEGER NOT NULL,
    local VARCHAR(120) NOT NULL,
    status VARCHAR(20) NOT NULL,
    campeonato_id BIGINT NOT NULL,
    mandante_id BIGINT NOT NULL,
    visitante_id BIGINT NOT NULL,
    CONSTRAINT fk_partida_campeonato
        FOREIGN KEY (campeonato_id) REFERENCES campeonatos(id),
    CONSTRAINT fk_partida_mandante
        FOREIGN KEY (mandante_id) REFERENCES equipes(id),
    CONSTRAINT fk_partida_visitante
        FOREIGN KEY (visitante_id) REFERENCES equipes(id)
);

CREATE INDEX idx_partidas_campeonato ON partidas(campeonato_id);
